 export const resObj=  [
    {
      id: 1,
      name: "Pizza Margherita",
      image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/800px-Pizza-3007395.jpg",
      description: "Classic Italian pizza with fresh mozzarella and basil.",
      price: "₹399",
      rating: 4.5,
      deliveryTime: "30 mins",
      tags: ["Italian", "Veg"],
    },
    {
      id: 2,
      name: "Chicken Biryani",
      image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/hyderabadi-biryani-recipe-chicken.jpg",
      description: "Aromatic and spicy chicken biryani with basmati rice.",
      price: "₹299",
      rating: 4.7,
      deliveryTime: "40 mins",
      tags: ["Indian", "Non-Veg"],
    },
    {
      id: 3,
      name: "Veggie Burger",
      image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2016/02/veg-burger-recipe-1.jpg",
      description: "Loaded veggie burger with cheese and fresh lettuce.",
      price: "₹199",
      rating: 4.2,
      deliveryTime: "20 mins",
      tags: ["American", "Veg"],
    },
    {
      id: 4,
      name: "Butter Chicken",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIIY2-O097dfAKBo7kq7jasEZA1Ed8fsSiPQ&s",
      description: "Creamy butter chicken served with naan.",
      price: "₹349",
      rating: 4.8,
      deliveryTime: "35 mins",
      tags: ["Indian", "Non-Veg"],
    },
    {
      id: 5,
      name: "Chocolate Shake",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdfDjYmsly2FXQGXGVXH6sPaNqUnMAmet64g&s",
      description: "Rich and creamy chocolate milkshake.",
      price: "₹149",
      rating: 4.3,
      deliveryTime: "15 mins",
      tags: ["Desserts", "Beverages"],
    },
  ];
  